### ISSUE TITLE
Item may not be null: IllegalArgumentException in ApiClient Line: 37

### ISSUE THREAD

**Issue by ilango123** [ubidots/ubidots-android-gps-tracker#2]
When I try to run in Android Studio, this is what I get:
This is interesting:
Uncaught Error: Java exception was raised during method invocation", source: https://app.ubidots.com/ (1)

**It is mostly because of this line in ApiClient:
String json = bridge.get("datasources");
bridge.get("datasources") returns a null and so json carries a null
Consequently, in the rawDataSources is also null.

List<Map<String, Object>> rawDataSources = gson.fromJson(json, List.class);
rawDataSources is null at this point

and so in the following line:
DataSource[] dataSources = new DataSource[rawDataSources.size()];
there is a NullPointerException because the call to size() naturally fails.**

12-14 15:40:38.865 2757-3868/com.ubidots.ubidots W/System.err: java.lang.IllegalArgumentException: Item may not be null
12-14 15:40:38.866 2757-3868/com.ubidots.ubidots W/System.err:     at org.apache.http.util.Args.notNull(Args.java:48)
12-14 15:40:38.866 2757-3868/com.ubidots.ubidots W/System.err:     at org.apache.http.config.RegistryBuilder.register(RegistryBuilder.java:58)
12-14 15:40:38.866 2757-3868/com.ubidots.ubidots W/System.err:     at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:727)
12-14 15:40:38.866 2757-3868/com.ubidots.ubidots W/System.err:     at com.ubidots.ubidots.ServerBridge.get(ServerBridge.java:179)
12-14 15:40:38.866 2757-3868/com.ubidots.ubidots W/System.err:     at com.ubidots.ubidots.ServerBridge.get(ServerBridge.java:154)
12-14 15:40:38.866 2757-3868/com.ubidots.ubidots W/System.err:     at com.ubidots.ubidots.ApiClient.getDataSources(ApiClient.java:37)
12-14 15:40:38.866 2757-3868/com.ubidots.ubidots W/System.err:     at com.ubidots.ubidots.fragments.BrowserFragment$WebViewJavascriptHandler.createDataSource(BrowserFragment.java:97)
12-14 15:40:38.866 2757-3868/com.ubidots.ubidots W/System.err:     at com.ubidots.ubidots.fragments.BrowserFragment$WebViewJavascriptHandler.sendToAndroid(BrowserFragment.java:84)
12-14 15:40:38.866 2757-3868/com.ubidots.ubidots W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
12-14 15:40:38.866 2757-3868/com.ubidots.ubidots W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
12-14 15:40:38.866 2757-3868/com.ubidots.ubidots W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
12-14 15:40:38.866 2757-3868/com.ubidots.ubidots W/System.err:     at android.os.Looper.loop(Looper.java:164)
12-14 15:40:38.866 2757-3868/com.ubidots.ubidots W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)
12-14 15:40:38.897 2757-3868/com.ubidots.ubidots W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
12-14 15:40:38.897 2757-3868/com.ubidots.ubidots W/System.err:     at com.ubidots.ubidots.ApiClient.getDataSources(ApiClient.java:42)
12-14 15:40:38.897 2757-3868/com.ubidots.ubidots W/System.err:     at com.ubidots.ubidots.fragments.BrowserFragment$WebViewJavascriptHandler.createDataSource(BrowserFragment.java:97)
12-14 15:40:38.897 2757-3868/com.ubidots.ubidots W/System.err:     at com.ubidots.ubidots.fragments.BrowserFragment$WebViewJavascriptHandler.sendToAndroid(BrowserFragment.java:84)
12-14 15:40:38.897 2757-3868/com.ubidots.ubidots W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
12-14 15:40:38.897 2757-3868/com.ubidots.ubidots W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
12-14 15:40:38.897 2757-3868/com.ubidots.ubidots W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
12-14 15:40:38.898 2757-3868/com.ubidots.ubidots W/System.err:     at android.os.Looper.loop(Looper.java:164)
12-14 15:40:38.898 2757-3868/com.ubidots.ubidots W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)
12-14 15:40:38.905 2757-2757/com.ubidots.ubidots I/chromium: [INFO:CONSOLE(1)] "Uncaught Error: **Java exception was raised during method invocation", source: https://app.ubidots.com/ (1)**
12-14 15:40:38.926 2757-2757/com.ubidots.ubidots W/zygote: Attempt to remove non-JNI local reference, dumping thread
12-14 15:40:38.936 2757-2769/com.ubidots.ubidots E/System: Uncaught exception thrown by finalizer
12-14 15:40:38.937 2757-2769/com.ubidots.ubidots E/System: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.concurrent.atomic.AtomicBoolean.compareAndSet(boolean, boolean)' on a null object reference
                                                               at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.shutdown(PoolingHttpClientConnectionManager.java:349)
                                                               at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.finalize(PoolingHttpClientConnectionManager.java:172)
                                                               at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
                                                               at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
                                                               at java.lang.Daemons$Daemon.run(Daemons.java:103)
                                                               at java.lang.Thread.run(Thread.java:764)

**Comment by ilango123** [comment]
I believe I have fixed this issue myself.  Instead of a blank white screen, I  am now able to see a screen. At this point I will consider this issue as closed.
![ubidots3](https://user-images.githubusercontent.com/25613858/34048579-da91ce9e-e179-11e7-842e-f1b0f7bff15b.JPG)
